version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: salon-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: salonAPI
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: janidu007/salon-backend:latest  
    container_name: salon-backend
    ports:
      - "9090:9090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/salonAPI
      SPRING_DATA_MONGODB_DATABASE: salonAPI
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: janidu007/salon-frontend:latest 
    container_name: salon-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
